version: 0.1.6
files:
  - url: https://github.com/Meet2304/Project-Linea/releases/download/v0.1.6/Linea-0.1.6.dmg
    sha512: D1JuXgO0aExJzMS5AVdRQsUBHYEIi9CaLPuf7iRR20CXgPfslxpZXrdkDX5u9mw9pX65Rfc2pvLvR1TsXZnYJw==
    size: 101636748
path: https://github.com/Meet2304/Project-Linea/releases/download/v0.1.6/Linea-0.1.6.dmg
sha512: D1JuXgO0aExJzMS5AVdRQsUBHYEIi9CaLPuf7iRR20CXgPfslxpZXrdkDX5u9mw9pX65Rfc2pvLvR1TsXZnYJw==
releaseDate: '2026-07-29T03:22:08.380Z'
